title = "HardPy TOML config"
tests_name = "Measurement"

[database]
user = "dev"
password = "dev"
host = "localhost"
port = 5984

[frontend]
host = "localhost"
port = 8000
language = "en"

[frontend.modal_result]
enable = false
auto_dismiss_pass = true
auto_dismiss_timeout = 5
