title = "HardPy TOML config"
tests_name = "StandCloud"

[database]
user = "dev"
password = "dev"
host = "localhost"
port = 5984

[frontend]
host = "localhost"
port = 8000
language = "en"

[frontend.modal_result]
enabled = true

[stand_cloud]
address = "demo.standcloud.localhost"
connection_only = true
