services:
  couchserver:
    image: couchdb:3.4
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: dev
      COUCHDB_PASSWORD: dev
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./database/couchdb.ini:/opt/couchdb/etc/local.ini

volumes:
  couchdb_data:
