title = "HardPy TOML config"
tests_name = "CouchDB Load"

[database]
user = "dev"
password = "dev"
host = "localhost"
port = 5984

[frontend]
host = "localhost"
port = 8000
language = "en"
full_size_button = false
sound_on = false
measurement_display = false

[frontend.modal_result]
enable = false
auto_dismiss_pass = true
auto_dismiss_timeout = 5
