title = "HardPy TOML config"
tests_name = "Minute Parity"

[database]
user = "dev"
password = "dev"
host = "localhost"
port = 5984

[frontend]
host = "localhost"
port = 8000
language = "ru"

[frontend.modal_result]
enabled = true
auto_dismiss_pass = true
auto_dismiss_timeout = 15000
